### ISSUE TITLE
A new expression requires (), [], or {} after type

### ISSUE THREAD

**Issue by meta-meta** [Benedicht/com.besthttp.profiler#1]
Hi, wanted to try out this package but we're on Unity 2020.3.44f1 and we're running up against:
```
Library\PackageCache\com.besthttp.profiler@b8048de18f\Runtime\Network\NetworkStats.cs(24,189): error CS1526: A new expression requires (), [], or {} after type
```

I believe it's due to these lines using a C# 9.0 language feature `target-typed new expressions` https://www.thomasclaudiushuber.com/2020/09/08/c-9-0-target-typed-new-expressions/

Unity does not switch to C#9 until 2021.2 https://docs.unity3d.com/2021.2/Documentation/Manual/CSharpCompiler.html

The docs here say 2020.1 or newer https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/addons/com.besthttp.profiler/profiler.html#network-profiler

> The profiler addon has a dependency on the [com.unity.profiling.core](https://docs.unity3d.com/Packages/com.unity.profiling.core@1.0/manual/index.html) that requires Unity 2020.1 or newer installations.

**Comment by meta-meta** [comment]
After changing all the `new()` expressions, I'm left with 1 error:
```
Library\PackageCache\com.besthttp.profiler@b8048de18f\Runtime\ProfilerUpdater.cs(24,20): error CS0426: The type name 'BufferPoolStats' does not exist in the type 'BufferPool'
```

From this line in `ProfilerUpdater.cs`: `BufferPool.BufferPoolStats bufferPoolStats = default;`

I can't find any definition for `BufferPool` or `BufferPoolStats`. Maybe it's in a new version of BestHTTP?

**Comment by Benedicht** [comment]
Fixed these issues a few months back, but it seems that i forgot to push it to the repo and got deleted in the meantime...

So, i pushed the changes to the repo, but i had to up the minimum Unity version to Unity 2021.2 because that's the first version that has the [ProfilerModule](https://docs.unity3d.com/2021.2/Documentation/ScriptReference/Unity.Profiling.Editor.ProfilerModule.html) class. I guess, i took granted that if the `com.unity.profiling.core` supports Unity 2020.1 then all the required classes are there, sorry.

**Comment by Benedicht** [comment]
`BufferPoolStats` should be there in the Best HTTP/2 package since ages, but make sure you are using the latest version (v2.8.6).

**Comment by meta-meta** [comment]
Thanks, we'll update to 2.8.6 and hopefully get around to updating Unity soon as well.
